name: Trigger Jenkins Job
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name:  'Jenkins Trigger Job (user-service-pharmacy-2021)'
        uses: appleboy/jenkins-action@master
        with:
          url: '${{ secrets.JENKINS_URL }}'
          user: '${{ secrets.JENKINS_USERNAME }}'
          job: '${{ secrets.JENKINS_JOB }}'
          token: '${{ secrets.JENKINS_TOKEN }}'
